title: 'b2a3e8.github.io'
description: "A jekyll theme inspired by linux consoles for hackers, developers and script kiddies."

header_pages:
  - index.md
  - vm.md
  - about.md
  - linux.md
  - contact.md
  - electronics.md

style: dark

include:
  - "_images"

footer: 'visit my github for various scripts and flushed out projects <a href="https://github.com/rommac100">github</a>

        All rights reserved unless specified otherwise'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
theme: jekyll-theme-console
