title: 'rommac100s personal website'
description: "A website dedicate to info dumping from various projects. Most of the time the dumps contain useful tips and tricks for anyone attempting to solve similar problems."

header_pages:
  - index.md
  - vm.md
  - about.md
  - linux.md
  - contact.md
  - electronics.md 
  - high_software.md

style: dark

include:
  - "_images"

footer: 'visit my github for various scripts and flushed out projects <a href="https://github.com/rommac100">github</a>

        All rights reserved unless specified otherwise'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
theme: jekyll-theme-console
